
#Config file for Clay WorldGen
[SETTINGS]

	#Spawn rate for Clay
	[SETTINGS."Spawn Rate"]
		#Diamond = 1 | Gold = 2 | | Redstone = 8 | Granite/Diorite/Andesite = 10 | Iron/Coal = 20
		#Range: 1 ~ 256
		spawnRate = 10

	#Maximum / Minimum Y-level to spawn Clay
	[SETTINGS."Spawn Level"]
		#Top offset of the Y-level Clay can spawn at
		#Range: 1 ~ 256
		topOffset = 8
		#Sets the maximum Y-level Clay can spawn below
		#Range: 1 ~ 256
		maxSpawnLevel = 256
		#Bottom offset of the Y-level Clay can spawn at
		#Range: 1 ~ 256
		botOffset = 8

	#Maximum vein size for Clay
	[SETTINGS."Vein Size"]
		#The vein size is randomized by default. This value only affect the max size a vein can potentially reach
		#Range: 1 ~ 256
		veinSize = 33

