#Min ticks for one clock cycle
#Range: > 2
min_clock_ticks = 2
#Max ticks for one clock cycle. Needs to be higher than min_clock_ticks
#Range: > 2
max_clock_ticks = 72000
#Min ticks for one clock pulse
#Range: > 1
min_clock_pulse_ticks = 1
#Max ticks for one clock pulse. Needs to be higher than min_clock_pulse_ticks
#Range: > 2
max_clock_pluse_ticks = 71000

