
[general]

	[general.general]
		#The base URL the API is exposed on, used for constructing URLs.
		apiBaseUrl = "http://localhost:3000/"
		#The port the API should be exposed on.
		apiPort = 3000
		#If the API should be enabled.
		startApi = true

[core]

	[core.general]
		#If an anonymous mod startup analytics request may be sent to our analytics service.
		analytics = true
		#If the version checker should be enabled.
		versionChecker = true

