#Write the recipe packet to a file. Useful for debugging.
dumpPacket = false
#Write statistics of the recipe packet size to the log
logPacketStats = true
#Controls different levels of debug output that can be useful for debugging issues
#Range: 0 ~ 2
debugLogLevel = 0
#Set to true to serialize and deserialize the recipe packet even in singleplayer.
#This is useless for anything but debugging issues
runSerializerInSingleplayer = false
#Prefix recipes by their length in the packet. This allows early detection of broken serializers
writeRecipeLength = false

