#Set the amount of power required to use use the personal shrinking device
setPowerUsage = 5000
#Set to true to enable power requirements for personal shrinking device
enablePowerRequirements = true
#Set the amount of power the personal shrinking device can store
setShrinkingDeviceCapacity = 100000

